security:
  firewalls:
    main:
      pattern: ^/
      provider: database_users
      form_login:
        login_path: login
        check_path: login
        default_target_path: /admin
      logout:
        path: /logout
        target: /
#      stateless: true

  access_control:
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/admin, roles: ROLE_ADMIN }

  providers:
    database_users:
      entity:
        class: App\Entity\User
        property: username

    in_memory:
      memory:
        users:
          admin:
            password: 'adminpassword'
            roles: 'ROLE_ADMIN'

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: auto

    App\Entity\User:
      algorithm: auto
